apiVersion: apps/v1
kind: Deployment
metadata:
  name: postgresql-deploy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgresql
  template:
    metadata:
      labels:
        app: postgresql
    spec:
      volumes:
        - name: postgresql-data
          emptyDir: {}
        - name: max-conns
          configMap:
            name: max-conns-cmap
      containers:
      - name: postgresql-container-test
        image: postgres
        ports:
        - containerPort: 5432
          protocol: TCP
        volumeMounts:
        - name: postgresql-data
          mountPath: /var/lib/pgsql/data
        - name: max-conns
          mountPath: /docker-entrypoint-initdb.d
        env:
          - name: POSTGRES_DB
            valueFrom:
              secretKeyRef:
                name: postgresql-my-first-secret
                key: database-name
          - name: POSTGRES_USER
            valueFrom:
              secretKeyRef:
                name: postgresql-my-first-secret
                key: database-user
          - name: POSTGRES_PASSWORD
            valueFrom:
              secretKeyRef:
                name: postgresql-my-first-secret
                key: database-password
          
