apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: sandbox
spec:
  selector:
    matchLabels:
      run: nginx
      app: dsp
  tier: frontend
  replicas: 2
  template:
    spec:
      containers:
      - name: nginx
        image: nginx
        volumeMounts:
          - mountPath: /etc/nginx
            name: nginx-conf
    volumes:
      - name: nginx-conf
        configMap:
          name: nginx-conf
          items:
            - key: nginx.conf
              path: nginx.conf


