apiVersion: v1
kind: Pod
metadata:
  name: busybox-new
spec:
  containers:
    - name: test-container-new
      image: registry.k8s.io/busybox
      command: [ "/bin/sh", "-c", "ls -la /etc/config" ]
      volumeMounts:
        - name: config-volume
          mountPath: /etc/config
  volumes:
    - name: config-volume
      configMap:
        name: my-files
  restartPolicy: Never
